version: "3.9"

services:

  mariadb:
    image: mariadb:11.4
    container_name: rtiqa-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - mariadb-data:/var/lib/mysql

  redis-cache:
    image: redis:7-alpine
    container_name: rtiqa-redis-cache
    restart: unless-stopped

  redis-queue:
    image: redis:7-alpine
    container_name: rtiqa-redis-queue
    restart: unless-stopped

  redis-socketio:
    image: redis:7-alpine
    container_name: rtiqa-redis-socketio
    restart: unless-stopped

volumes:
  mariadb-data:
